* Outline
** Purpose
 - The purpose of this project is to attempt to ready myself for life outside
   the university. One of the goals of this project is to help me spend as
   little time outside the university as possible. In producing this paper, I
   attempt to anticipate[slide] the components of a proposal for a
   finger-style guitar program which would most likely entice or convince an
   institution of higher education of the importance of offering such a
   program. I then prepare[slide] for as many anticipated components as
   possible. At the moment I see this as entailing three different
   tactics[slide]: situating[slide] the guitar within its contexts;
   projecting[slide] into the future (think anticipation); and
   professional[slide] development of myself as an instructor.
** Tactics
 - Situation: placing finger-style guitar within its contexts both
   contemporary and historical.

 - Projection: attempting to anticipate changes in finger-style guitar
   instruction, performance, and composition as a way in which to
   excite. Also, a projection into the benefits that a university may
   experience with the inclusion of a finger-style program.

 - Personal Growth: Curriculum Vitae
*** Situation
**** Contextualization
 - Situate finger-style as a manner of playing the instrument within different
   contexts[slide]. Historical: race and hillbilly records, Ragtime, parlor
   guitar. Regional: Hawaiian, Russian, Venezuala/Argentina/South America,
   British, French... By Genre: Rock, hip hop, indie, finger-style as a
   genre...
**** Historiography
 - Be prepared to answer all manner of questions relating to the history of
   finger-style guitar and the guitar in general. Due to the nature of playing
   the instrument, be prepared to answer major questions about the
   lute---mostly relating to the renaissance and baroque lutes.

 - Most importantly, known the history of finger-style guitar as a genre. This
   cannot but be a biased account of the history. I think that we must embrace
   this bias and give the best account possible knowing that we can change our
   understanding of history with new evidence.
*** Projection
**** Future Developments
 - Anticipate[slide], as thoroughly as possible, the potential avenues in
   which finger-style guitar may travel. Anticipate its popularity by
   reflecting on how it has been growing. If possible, use qualitative
   information to do this.

 - Other disciplines within the musical academy seem to have canonized their
   repertoire. Is this desirable? Should the music of finger-style guitar as a
   genre be canonized? Or is it more helpful for the music to resist
   canonization? Is it better to be inclusive or exclusive?
   - One interesting area to think about would be the difference in repertoire
     from 2006 to 2017. The amount of repertoire available to the student of
     finger-style guitar in 2006 was much less than the student of 2017. Is
     this a good thing? I am reminded of /The Paradox of Choice: Why More is
     Less/ (2004) by American psychologist Barry Schwartz.

**** Potential Gains
 - Think about different ways in which the offering a finger-style guitar track
   in a guitar program could benefit a university.
 - From a monetary point of view, it is possible, due to the rising popularity
   of finger-style guitar as a genre, that a school, with the right backing,
   marketing, and encouragement, could generate a hefty amount of cash from
   bringing in students from all of the world to study at their university.
 - A more practical gain, and certainly one which I would find more interest,
   is in the scholarly gains which could be had from offering a program. I can
   see it now, a university which able to establish the relationship between
   the parlor guitar, the Sears-Roebuck Catalog, and the rise of folk music in
   the United States through the thread of finger-style guitar.
   - I can see a peer-reviewed journal published by a university guitar
     program, a feat which I am unaware of in general let alone for a
     finger-style program.
 - Can you think of other ways in which a university might benefit from having
   a finger-style guitar track?
*** Personal Growth
**** Compositions
 - The production of an album of music may help to establish my credibility.
 - The actual composition of music seems to set the finger-style guitarist
   apart from his or her classical, nylon-string guitar counterpart
**** Performances
 - Prestigious performances all of the globe
**** Publications
 - Magazines, Music Blogs, Scholarly Journals, Transcriptions and other Sheet
   Music, books
**** Other Ideas?
 - Can you think of other ways in which a finger-style guitarist could help
   establish his or her credibility in the eyes of a university

** Institutions
 - This list is far too short. There must be others out there that teach
   finger-style guitar at the collegiate level. Some of them, like a few I am
   about to mention, probably offer finger-style lessons but do not advertise
   as such.
 - While I wanted to add Antoine Dufour and Adam Cord to this list, I was
   unable to determine the institution with which they were respectively
   associated.
 - Michael Chapdelaine teaches classical and finger-style guitar at the
   University of New Mexico. In an interview, he stated that he blurs the
   lines between classical and finger-style. Once a student has reached a
   certain level he or she is able to study finger-style guitar.
 - Sean McGowan teaching finger-style jazz and commercial guitar at the
   University of Colorado-Denver. I look forward to speaking with him about
   his pedagogical approaches. Alex de Grassi stated in an interview that
   McGowan offers a class on finger-style guitar which uses both de Grassi and
   McGowen's respective finger-style methods. McGowan's being a jazz
   finger-style method.
 - Michael Millham teaches classical guitar at Eastern Washington
   University. Will Boulé and Alex de Grassi indicates that he offers
   finger-style lessons.
 - John Stropes is no stranger to anyone here. It is worth noting that John
   Stropes has a long history in guitar instruction and publication. The UWM
   program was initially formed through a joint venture with the Wisconsin
   Conservatory of Music and UWM. John can you speak a little about the
   creation of this program?

** Interviews
 - I plan to interview the people that I have just mentioned in order to
   determine out how they got where they are and how I can get there.
 - I am also looking for recommendations from these individuals for a course
   of action.

** Elevators
 - I do not currently have an elevator speech for this paper. I anticipate
   that this will be the most difficult aspect of this work. It will be like a
   puzzle in the removal and movement of text will result in a different
   picture. 

** Conclusion
 - In conclusion, this paper is designed to be as practical as possible. In
   doing so, it has become massive. I will not be able to get to everything
   that I have talked about. I do not anticipate that this will be an easy
   process. Like those trail blazers before me, I hope to find a path which
   will lead toward the benefit of finger-style guitar and the
   self-sufficiency that is a hallmark of success.

Thank you.

